# Generated by Django 3.2.5 on 2021-11-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luv_bug_gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='create_gallery_images')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luv_bug_gallery.creategallery')),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImages',
        ),
    ]
