# Generated by Django 3.2.5 on 2021-11-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luv_bug_gallery', '0002_auto_20211107_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategallery',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
